### PR TITLE
Fixes #46 - Check length of arguments before accessing array

### LINKED ISSUE #46: `convox env get` crashes if no var argument supplied
(master) ~/Code/sinatra$ convox env get 
panic: runtime error: index out of range

goroutine 16 [running]: 
runtime.panic(0x468f20, 0x7ad73c) 
/usr/lib/go/src/pkg/runtime/panic.c:279 +0xf5 
main.cmdEnvGet(0x20891c2a0) 
/go/src/github.com/convox/cli/convox/env.go:88 +0x2ad 
github.com/convox/cli/Godeps/_workspace/src/github.com/codegangsta/cli.Command.Run(0x4d17d0, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4e9350, 0x8, 0x0, ...) 
/go/src/github.com/convox/cli/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:118 +0xec6 
github.com/convox/cli/Godeps/_workspace/src/github.com/codegangsta/cli.(*App).RunAsSubcommand(0x2089061e0, 0x20891c0e0, 0x0, 0x0) 
/go/src/github.com/convox/cli/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:270 +0xae1 
github.com/convox/cli/Godeps/_workspace/src/github.com/codegangsta/cli.Command.startApp(0x4d0830, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4f0b70, 0xd, 0x55a9d0, ...) 
/go/src/github.com/convox/cli/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:176 +0x221 
github.com/convox/cli/Godeps/_workspace/src/github.com/codegangsta/cli.Command.Run(0x4d0830, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4f0b70, 0xd, 0x55a9d0, ...) 
/go/src/github.com/convox/cli/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:45 +0x12fc 
github.com/convox/cli/Godeps/_workspace/src/github.com/codegangsta/cli.(*App).Run(0x2089060f0, 0x20889a000, 0x3, 0x3, 0x0, 0x0) 
/go/src/github.com/convox/cli/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:177 +0xbb8 
main.main() 
/go/src/github.com/convox/cli/convox/main.go:45 +0x7d

goroutine 19 [finalizer wait]: 
runtime.park(0x31ab0, 0x7d53b0, 0x7b04c9) 
/usr/lib/go/src/pkg/runtime/proc.c:1369 +0x89 
runtime.parkunlock(0x7d53b0, 0x7b04c9) 
/usr/lib/go/src/pkg/runtime/proc.c:1385 +0x3b 
runfinq() 
/usr/lib/go/src/pkg/runtime/mgc0.c:2644 +0xcf 
runtime.goexit() 
/usr/lib/go/src/pkg/runtime/proc.c:1445

goroutine 20 [runnable]: 
os/signal.loop() 
/usr/lib/go/src/pkg/os/signal/signal_unix.go:19 
created by os/signal.init·1 
/usr/lib/go/src/pkg/os/signal/signal_unix.go:27 +0x32 
```

### PR DESCRIPTION
**Pull request by stevenbrichards**
See #46

### CODE REVIEW

**Comment by stevenbrichards** [comment]
This test failed:
```
--- FAIL: TestLoginHost (0.03s)
	main_test.go:82: Expected ERROR: Get https://BAD/apps: dial tcp: lookup BAD: no such host
		 (type string) - Got ERROR: Get https://BAD/apps: dial tcp: lookup BAD on 10.1.0.2:53: no such host
		 (type string)
``` 
Seems unrelated to my changes.

**Comment by ddollar** [comment]
This looks good but would you please run `gofmt` across it and rebase to master. Thank you :)

**Comment by josegonzalez** [comment]
@ddollar pretty sure #52 covers this.

**Comment by ddollar** [comment]
Ah, perfect. Thanks then :)

**Pull request closed without merging**
