### PR TITLE
adds progress bars during build upload

### PR DESCRIPTION
**Pull request by bobzoller**
`convox build` was sitting at `Uploading... OK` for a long time with no output, and I thought something was broken.  Turns out it was just taking 30 minutes to upload the tarball.

This PR adds progress bars during the tarball upload, and also fixes the log messages to match reality: tarball step says `Preparing tarball...`, upload step says `Uploading...`

### CODE REVIEW

**Comment by ddollar** [comment]
If this is taking 30 minutes to upload I'd like to find a better solution overall. Do you have a very large code directory?

**Comment by bobzoller** [comment]
1Mb/s Internet uplink.

**Comment by bobzoller** [comment]
Of course as I move the builds to CI this won't matter (as much), but it's
worth doing something because as a first experience I think it erodes
confidence.

**Comment by csquared** [comment]
We moved this repo - do you mind re-issuing the PR over there?

**Comment by bobzoller** [comment]
this PR doesn't translate directly to the new world.

New-world-wise -- if `Client.PostMultipart` took a param to enable progress bars (or a [functional option](http://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis) or something), then `executeBuild` in cmd/convox/builds.go could use enable it.  @ddollar if you're into that I'm happy to take another crack (would welcome explicit guidance as I'm still a Go newb), but otherwise I'll let this die.

**Pull request closed without merging**
