### PR TITLE
WIP: Non Lambda Regions

### PR DESCRIPTION
**Pull request by rjocoleman**
ref #38 

__UPDATE:__ this needs reworking since configurable (lambda) regions hit

`us-east-1` is great, but `ap-southeast-2` is better for my users. How do you feel about a PR to make stack region configurable?

Something like this?

```go
cli.StringFlag{
	Name: "region",
	Value: "us-east-1",
	Usage: "AWS Region",
	EnvVar: "AWS_REGION",
},
```

or a more consistent:

```go
region := os.Getenv("AWS_REGION")
if region == "" {
    region = "us-east-1"
}
```

The tricky part is Lambda isn't available in all regions so I'd first need to create a separate CloudFormation stack in `us-east-1` for the Lambda function, then reference that by ARN in the main CloudFormation stack. `"Fn::Join": [ "", [ "arn:aws:lambda:us-east-1:", { "Ref": "AWS::AccountId" }, ":function:", {"Ref" : "LambdaFunctionName"} ] ]` or so

### CODE REVIEW

**Comment by rjocoleman** [comment]
This is a WIP now.

As per my last comment, it's using the the SNS/lambda architecture.
Slight change it's using two cloudformation stacks and creating the SNS topic then setting the permissions manually.

TODO:

- [ ] Changes to convox/kernel formation definitions to match this architecture (i.e. `kernel.json`, `lambda.json`)
- [ ] Uninstall/teardown
- [ ] Fix something in convox/kernel lambda bridge function (`formation`) to actually work with the response

**Comment by ddollar** [comment]
Could we put the .zip for the lambda function in S3 in every region? If we do that it should be possible to create the CustomTopic Lambda function in any desired region unless I am mistaken.

**Comment by rjocoleman** [comment]
> Could we put the .zip for the lambda function in S3 in every region?

Lambda's only in a few regions :cry: https://docs.aws.amazon.com/general/latest/gr/rande.html#lambda_region

**Comment by ddollar** [comment]
Ahh, gotcha. This approach seems to make sense then. We used a similar setup before Lambda support was added to CloudFormation.

**Comment by rjocoleman** [comment]
I think this side is pretty much done.

I just need to handle AZs and Subnets in a more flexible way in the Cloudformation stack over in https://github.com/convox/kernel/pull/95

But as it stands I can install and uninstall in other regions with this PR and https://github.com/convox/kernel/pull/95

**Comment by pscanf** [comment]
:+1:  on this feature

@rjocoleman: I would suggest to keep the CustomTopic lambda in the same region as the other resources if AWS Lambda is available in that region, so that it's easier for the user to keep an eye on all resources.

Also, the Lambda SNS bridge could be employed only if AWS Lambda is not available in the chosen region (keeping everything in the same CloudFormation configuration would probably be preferable). This way this workaround, which right now is definitely necessary, could just be removed once Lambda is supported everywhere.

/random-suggestions
:-)

**Comment by rjocoleman** [comment]
I've rebased this to resolve conflicts.

**Comment by gjohnson** [comment]
Awesome, looking forward to this.

**Comment by rjocoleman** [comment]
replaced by #82

**Pull request closed without merging**
