### PR TITLE
Debug deploy

### PR DESCRIPTION
**Pull request by nzoschke**

### CODE REVIEW

**Comment by nzoschke** [comment]
If run as `DEBUG=1 convox ...` this prints extra debugging information for the start and login exec path, build tar path, and a couple of the deploy HTTP requests.

**Comment by nzoschke** [comment]
This debug path proved helpful in figuring out why both start and deploy were broken. This PR also has a patch that fixes that, around the docker --tlsverify option.

**Comment by nzoschke** [comment]
This also includes a speculative patch to an observed panic in the tar path.

**Comment by mattmanning** [comment]
Looks good. :+1:  Would be nice to fix tests before shipping.

**Pull request merged**
