### PR TITLE
Attached run

### PR DESCRIPTION
**Pull request by nzoschke**
Client for:

https://github.com/convox/kernel/blob/master/web.go#L114
https://github.com/convox/kernel/blob/master/controllers/processes.go#L129
https://github.com/convox/kernel/blob/master/models/process.go#L258

The kernel connects a websocket to the docker container with AttachToContainer

### CODE REVIEW

**Comment by nzoschke** [comment]
Currently this does not handle terminal control characters well at all.

```
$ convox run --app worker --attach worker1 sh
/go/src/github.com/convox-examples/worker # ls -al
ls -al
total 28
drwxr-xr-x    3 root     root          4096 Aug 14 17:08 .
drwxr-xr-x    3 root     root          4096 Aug 14 17:08 ..
drwxr-xr-x    7 root     root          4096 Aug 14 17:08 .git
-rw-r--r--    1 root     root           215 Jul 18 20:09 Dockerfile
-rw-r--r--    1 root     root            23 Jul 18 20:09 Procfile
-rw-r--r--    1 root     root             0 Aug 14 15:10 Readme.md
-rw-r--r--    1 root     root            40 Aug 14 17:08 docker-compose.yml
-rw-r--r--    1 root     root           208 Aug 14 17:08 worker.go
/go/src/github.com/convox-examples/worker # ^[[A^[[D^[[C^[[A^[[B
/go/src/github.com/convox-examples/worker # ^D
^C
```

**Comment by bgentry** [comment]
@nzoschke how about exit status? is that preserved?

**Comment by nzoschke** [comment]
@bgentry not yet but you better believe we'll get it working well this time :)

**Comment by bgentry** [comment]
> you better believe we'll get it working well this time :)

8 years and counting :calendar:

**Pull request merged**
